CURRENT_PATH="$(cd `dirname $0`; pwd)"
BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMMIT=$(git rev-parse --short HEAD)
VERSION=$(cat $CURRENT_PATH/version)

echo "# Auto-generated by build script
VERSION = '${VERSION}'
BUILD_TIME = '$(date)'
GIT_BRANCH = '${BRANCH}'
GIT_COMMIT = '${COMMIT}'" > ./app/version.py