BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMMIT=$(git rev-parse --short HEAD)

echo "# Auto-generated by build script
BUILD_TIME = '$(date)'
GIT_BRANCH = '${BRANCH}'
GIT_COMMIT = '${COMMIT}'" > ./app/version.py